export const metadata = {
    title: "Your Website",
    description: "Generated by create next app",
  };
  window.addEventListener('scroll', function() {
    
    console.log('User is scrolling');
});
window.addEventListener('resize', function() {
  
  console.log('Window resized');
});


